[build]
  base = "./"
  command = "yarn build:app"
  publish = "packages/app/public"

[context.storybook-master]
  publish = "./"
  command = "exit 0"

# [dev]
#   command = "yarn --cwd packages/app run develop"
#   targetPort = 3000
[dev]
  command   = "yarn --cwd packages/app run develop"
  targetPort = 8000
  publish   = "packages/app/public"