name: Storybook
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    env:
      NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          yarn
          yarn build:storybook -- --output-dir ../../storybook-static
          cp netlify.toml storybook-static/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: storybook-master
          FOLDER: storybook-static
